// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: proto/internal.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTunnelRequest) Reset() {
	*x = FindTunnelRequest{}
	mi := &file_proto_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTunnelRequest) ProtoMessage() {}

func (x *FindTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTunnelRequest.ProtoReflect.Descriptor instead.
func (*FindTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0}
}

func (x *FindTunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type FindTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// The address of the node handling the tunnel.
	// If found is true, this will be the address of the node.
	// The caller can then use this address to forward the request.
	NodeAddress   string `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTunnelResponse) Reset() {
	*x = FindTunnelResponse{}
	mi := &file_proto_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTunnelResponse) ProtoMessage() {}

func (x *FindTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTunnelResponse.ProtoReflect.Descriptor instead.
func (*FindTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1}
}

func (x *FindTunnelResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindTunnelResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

type ForwardUdpPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	SourceAddress string                 `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardUdpPacketRequest) Reset() {
	*x = ForwardUdpPacketRequest{}
	mi := &file_proto_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardUdpPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardUdpPacketRequest) ProtoMessage() {}

func (x *ForwardUdpPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardUdpPacketRequest.ProtoReflect.Descriptor instead.
func (*ForwardUdpPacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardUdpPacketRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *ForwardUdpPacketRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *ForwardUdpPacketRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ForwardUdpPacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResponseData  []byte                 `protobuf:"bytes,2,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardUdpPacketResponse) Reset() {
	*x = ForwardUdpPacketResponse{}
	mi := &file_proto_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardUdpPacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardUdpPacketResponse) ProtoMessage() {}

func (x *ForwardUdpPacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardUdpPacketResponse.ProtoReflect.Descriptor instead.
func (*ForwardUdpPacketResponse) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardUdpPacketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardUdpPacketResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

func (x *ForwardUdpPacketResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_internal_proto protoreflect.FileDescriptor

const file_proto_internal_proto_rawDesc = "" +
	"\n" +
	"\x14proto/internal.proto\x12\binternal\"0\n" +
	"\x11FindTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"M\n" +
	"\x12FindTunnelResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\"q\n" +
	"\x17ForwardUdpPacketRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"~\n" +
	"\x18ForwardUdpPacketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rresponse_data\x18\x02 \x01(\fR\fresponseData\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xb5\x01\n" +
	"\x0fInternalService\x12G\n" +
	"\n" +
	"FindTunnel\x12\x1b.internal.FindTunnelRequest\x1a\x1c.internal.FindTunnelResponse\x12Y\n" +
	"\x10ForwardUdpPacket\x12!.internal.ForwardUdpPacketRequest\x1a\".internal.ForwardUdpPacketResponseB0Z.github.com/ehrlich-b/tunn/pkg/proto/internalv1b\x06proto3"

var (
	file_proto_internal_proto_rawDescOnce sync.Once
	file_proto_internal_proto_rawDescData []byte
)

func file_proto_internal_proto_rawDescGZIP() []byte {
	file_proto_internal_proto_rawDescOnce.Do(func() {
		file_proto_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_internal_proto_rawDesc), len(file_proto_internal_proto_rawDesc)))
	})
	return file_proto_internal_proto_rawDescData
}

var file_proto_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_internal_proto_goTypes = []any{
	(*FindTunnelRequest)(nil),        // 0: internal.FindTunnelRequest
	(*FindTunnelResponse)(nil),       // 1: internal.FindTunnelResponse
	(*ForwardUdpPacketRequest)(nil),  // 2: internal.ForwardUdpPacketRequest
	(*ForwardUdpPacketResponse)(nil), // 3: internal.ForwardUdpPacketResponse
}
var file_proto_internal_proto_depIdxs = []int32{
	0, // 0: internal.InternalService.FindTunnel:input_type -> internal.FindTunnelRequest
	2, // 1: internal.InternalService.ForwardUdpPacket:input_type -> internal.ForwardUdpPacketRequest
	1, // 2: internal.InternalService.FindTunnel:output_type -> internal.FindTunnelResponse
	3, // 3: internal.InternalService.ForwardUdpPacket:output_type -> internal.ForwardUdpPacketResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_internal_proto_init() }
func file_proto_internal_proto_init() {
	if File_proto_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_internal_proto_rawDesc), len(file_proto_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_proto_goTypes,
		DependencyIndexes: file_proto_internal_proto_depIdxs,
		MessageInfos:      file_proto_internal_proto_msgTypes,
	}.Build()
	File_proto_internal_proto = out.File
	file_proto_internal_proto_goTypes = nil
	file_proto_internal_proto_depIdxs = nil
}
