// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/tunnel.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelMessage is the envelope for all control plane and data plane messages.
// This allows multiple message types to be sent over a single bidirectional stream.
type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TunnelMessage_RegisterClient
	//	*TunnelMessage_RegisterResponse
	//	*TunnelMessage_ProxyRequest
	//	*TunnelMessage_ProxyResponse
	//	*TunnelMessage_HealthCheck
	//	*TunnelMessage_HealthCheckResponse
	//	*TunnelMessage_HttpRequest
	//	*TunnelMessage_HttpResponse
	//	*TunnelMessage_StreamClosed
	//	*TunnelMessage_UdpPacket
	Message       isTunnelMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetMessage() isTunnelMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TunnelMessage) GetRegisterClient() *RegisterClient {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_RegisterClient); ok {
			return x.RegisterClient
		}
	}
	return nil
}

func (x *TunnelMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetProxyRequest() *ProxyRequest {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_ProxyRequest); ok {
			return x.ProxyRequest
		}
	}
	return nil
}

func (x *TunnelMessage) GetProxyResponse() *ProxyResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_ProxyResponse); ok {
			return x.ProxyResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetHealthCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *TunnelMessage) GetHealthCheckResponse() *HealthCheckResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HealthCheckResponse); ok {
			return x.HealthCheckResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetStreamClosed() *StreamClosed {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_StreamClosed); ok {
			return x.StreamClosed
		}
	}
	return nil
}

func (x *TunnelMessage) GetUdpPacket() *UdpPacket {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_UdpPacket); ok {
			return x.UdpPacket
		}
	}
	return nil
}

type isTunnelMessage_Message interface {
	isTunnelMessage_Message()
}

type TunnelMessage_RegisterClient struct {
	RegisterClient *RegisterClient `protobuf:"bytes,1,opt,name=register_client,json=registerClient,proto3,oneof"`
}

type TunnelMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type TunnelMessage_ProxyRequest struct {
	ProxyRequest *ProxyRequest `protobuf:"bytes,3,opt,name=proxy_request,json=proxyRequest,proto3,oneof"`
}

type TunnelMessage_ProxyResponse struct {
	ProxyResponse *ProxyResponse `protobuf:"bytes,4,opt,name=proxy_response,json=proxyResponse,proto3,oneof"`
}

type TunnelMessage_HealthCheck struct {
	HealthCheck *HealthCheck `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type TunnelMessage_HealthCheckResponse struct {
	HealthCheckResponse *HealthCheckResponse `protobuf:"bytes,6,opt,name=health_check_response,json=healthCheckResponse,proto3,oneof"`
}

type TunnelMessage_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,7,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type TunnelMessage_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,8,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type TunnelMessage_StreamClosed struct {
	StreamClosed *StreamClosed `protobuf:"bytes,9,opt,name=stream_closed,json=streamClosed,proto3,oneof"`
}

type TunnelMessage_UdpPacket struct {
	UdpPacket *UdpPacket `protobuf:"bytes,10,opt,name=udp_packet,json=udpPacket,proto3,oneof"`
}

func (*TunnelMessage_RegisterClient) isTunnelMessage_Message() {}

func (*TunnelMessage_RegisterResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_ProxyRequest) isTunnelMessage_Message() {}

func (*TunnelMessage_ProxyResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_HealthCheck) isTunnelMessage_Message() {}

func (*TunnelMessage_HealthCheckResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_HttpRequest) isTunnelMessage_Message() {}

func (*TunnelMessage_HttpResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_StreamClosed) isTunnelMessage_Message() {}

func (*TunnelMessage_UdpPacket) isTunnelMessage_Message() {}

// RegisterClient is sent by the client (tunn serve) when it first connects
// to register a new tunnel with the proxy server.
type RegisterClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel_id is a unique identifier for this tunnel (can be generated client-side)
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	// target_url is the local service to forward requests to (e.g., "http://localhost:8000")
	TargetUrl string `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	// auth_token is the JWT from `tunn login` (contains creator's email)
	AuthToken string `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	// creator_email is extracted from the JWT (email of tunnel creator)
	CreatorEmail string `protobuf:"bytes,4,opt,name=creator_email,json=creatorEmail,proto3" json:"creator_email,omitempty"`
	// allowed_emails is the list of emails that can access this tunnel (Google Doc model)
	// The creator_email is automatically included
	AllowedEmails []string `protobuf:"bytes,5,rep,name=allowed_emails,json=allowedEmails,proto3" json:"allowed_emails,omitempty"`
	// tunnel_key is the secret that allows creating tunnels
	// V1: WELL_KNOWN_KEY (free for everyone)
	// V2: Remove this, check subscription via tunn-auth instead
	TunnelKey string `protobuf:"bytes,6,opt,name=tunnel_key,json=tunnelKey,proto3" json:"tunnel_key,omitempty"`
	// protocol specifies what protocol this tunnel supports: "http", "udp", or "both"
	// Default: "http" for backwards compatibility
	Protocol string `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// udp_target_address is the local UDP service to forward packets to (e.g., "localhost:25565")
	// Only used when protocol is "udp" or "both"
	UdpTargetAddress string `protobuf:"bytes,8,opt,name=udp_target_address,json=udpTargetAddress,proto3" json:"udp_target_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterClient) Reset() {
	*x = RegisterClient{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClient) ProtoMessage() {}

func (x *RegisterClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClient.ProtoReflect.Descriptor instead.
func (*RegisterClient) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClient) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RegisterClient) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *RegisterClient) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterClient) GetCreatorEmail() string {
	if x != nil {
		return x.CreatorEmail
	}
	return ""
}

func (x *RegisterClient) GetAllowedEmails() []string {
	if x != nil {
		return x.AllowedEmails
	}
	return nil
}

func (x *RegisterClient) GetTunnelKey() string {
	if x != nil {
		return x.TunnelKey
	}
	return ""
}

func (x *RegisterClient) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RegisterClient) GetUdpTargetAddress() string {
	if x != nil {
		return x.UdpTargetAddress
	}
	return ""
}

// RegisterResponse is sent by the server to acknowledge tunnel registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether registration succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains details if success is false
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// public_url is the publicly accessible URL for this tunnel (e.g., "https://abc123.tunn.to")
	PublicUrl     string `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

// ProxyRequest is sent by the server to instruct the client to open a new
// data connection for forwarding an incoming request.
type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id uniquely identifies this proxy connection
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// source_address is the remote client's address (for logging/debugging)
	SourceAddress string `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

// ProxyResponse is sent by the client to acknowledge a ProxyRequest.
type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id matches the ProxyRequest
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// success indicates whether the client successfully opened the data connection
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains details if success is false
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthCheck is a ping message sent by either side to keep the connection alive.
type HealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the sender's current time in Unix milliseconds
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckResponse is a pong message sent in response to a HealthCheck.
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the original HealthCheck timestamp (for RTT calculation)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// response_timestamp is the responder's current time in Unix milliseconds
	ResponseTimestamp int64 `protobuf:"varint,2,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetResponseTimestamp() int64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

// HttpRequest is sent by the server to the client with the full HTTP request
// that needs to be proxied to the local target.
type HttpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id uniquely identifies this HTTP request/response pair
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// method is the HTTP method (GET, POST, etc.)
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// path is the HTTP path (e.g., "/api/users")
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// headers is a map of HTTP header names to values
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body is the HTTP request body (may be empty)
	Body          []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *HttpRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse is sent by the client to the server with the HTTP response
// from the local target.
type HttpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id matches the HttpRequest
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// status_code is the HTTP status code (e.g., 200, 404)
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// headers is a map of HTTP header names to values
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// body is the HTTP response body
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *HttpResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// StreamClosed is sent by either side to indicate a connection has closed.
type StreamClosed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id identifies which connection closed
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// reason describes why the connection closed (for logging)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClosed) Reset() {
	*x = StreamClosed{}
	mi := &file_proto_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClosed) ProtoMessage() {}

func (x *StreamClosed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClosed.ProtoReflect.Descriptor instead.
func (*StreamClosed) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *StreamClosed) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *StreamClosed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// UdpPacket is sent bidirectionally to tunnel UDP packets through the gRPC stream.
// The proxy sends packets received from public internet to the serve client.
// The serve client sends response packets from the local UDP target back to the proxy.
type UdpPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel_id identifies which tunnel this packet belongs to
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	// source_address is the IP:port of the original UDP sender (for routing responses)
	// Format: "192.168.1.100:12345"
	SourceAddress string `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	// destination_address is the IP:port of the destination (for routing on client side)
	// Format: "localhost:25565"
	DestinationAddress string `protobuf:"bytes,3,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// data is the raw UDP packet payload
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// from_client indicates direction: true = from serve client to proxy, false = from proxy to serve client
	FromClient bool `protobuf:"varint,5,opt,name=from_client,json=fromClient,proto3" json:"from_client,omitempty"`
	// timestamp_ms is when the packet was received (Unix milliseconds)
	TimestampMs   int64 `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpPacket) Reset() {
	*x = UdpPacket{}
	mi := &file_proto_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpPacket) ProtoMessage() {}

func (x *UdpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpPacket.ProtoReflect.Descriptor instead.
func (*UdpPacket) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *UdpPacket) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *UdpPacket) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *UdpPacket) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *UdpPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UdpPacket) GetFromClient() bool {
	if x != nil {
		return x.FromClient
	}
	return false
}

func (x *UdpPacket) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\atunn.v1\"\xa2\x05\n" +
	"\rTunnelMessage\x12B\n" +
	"\x0fregister_client\x18\x01 \x01(\v2\x17.tunn.v1.RegisterClientH\x00R\x0eregisterClient\x12H\n" +
	"\x11register_response\x18\x02 \x01(\v2\x19.tunn.v1.RegisterResponseH\x00R\x10registerResponse\x12<\n" +
	"\rproxy_request\x18\x03 \x01(\v2\x15.tunn.v1.ProxyRequestH\x00R\fproxyRequest\x12?\n" +
	"\x0eproxy_response\x18\x04 \x01(\v2\x16.tunn.v1.ProxyResponseH\x00R\rproxyResponse\x129\n" +
	"\fhealth_check\x18\x05 \x01(\v2\x14.tunn.v1.HealthCheckH\x00R\vhealthCheck\x12R\n" +
	"\x15health_check_response\x18\x06 \x01(\v2\x1c.tunn.v1.HealthCheckResponseH\x00R\x13healthCheckResponse\x129\n" +
	"\fhttp_request\x18\a \x01(\v2\x14.tunn.v1.HttpRequestH\x00R\vhttpRequest\x12<\n" +
	"\rhttp_response\x18\b \x01(\v2\x15.tunn.v1.HttpResponseH\x00R\fhttpResponse\x12<\n" +
	"\rstream_closed\x18\t \x01(\v2\x15.tunn.v1.StreamClosedH\x00R\fstreamClosed\x123\n" +
	"\n" +
	"udp_packet\x18\n" +
	" \x01(\v2\x12.tunn.v1.UdpPacketH\x00R\tudpPacketB\t\n" +
	"\amessage\"\xa0\x02\n" +
	"\x0eRegisterClient\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12#\n" +
	"\rcreator_email\x18\x04 \x01(\tR\fcreatorEmail\x12%\n" +
	"\x0eallowed_emails\x18\x05 \x03(\tR\rallowedEmails\x12\x1d\n" +
	"\n" +
	"tunnel_key\x18\x06 \x01(\tR\ttunnelKey\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12,\n" +
	"\x12udp_target_address\x18\b \x01(\tR\x10udpTargetAddress\"p\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\"Z\n" +
	"\fProxyRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"s\n" +
	"\rProxyResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"+\n" +
	"\vHealthCheck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"b\n" +
	"\x13HealthCheckResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12response_timestamp\x18\x02 \x01(\x03R\x11responseTimestamp\"\xeb\x01\n" +
	"\vHttpRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12;\n" +
	"\aheaders\x18\x04 \x03(\v2!.tunn.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\fHttpResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".tunn.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\fStreamClosed\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd8\x01\n" +
	"\tUdpPacket\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x03 \x01(\tR\x12destinationAddress\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1f\n" +
	"\vfrom_client\x18\x05 \x01(\bR\n" +
	"fromClient\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs2V\n" +
	"\rTunnelService\x12E\n" +
	"\x0fEstablishTunnel\x12\x16.tunn.v1.TunnelMessage\x1a\x16.tunn.v1.TunnelMessage(\x010\x01B-Z+github.com/behrlich/tunn/pkg/proto/tunnelv1b\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_tunnel_proto_goTypes = []any{
	(*TunnelMessage)(nil),       // 0: tunn.v1.TunnelMessage
	(*RegisterClient)(nil),      // 1: tunn.v1.RegisterClient
	(*RegisterResponse)(nil),    // 2: tunn.v1.RegisterResponse
	(*ProxyRequest)(nil),        // 3: tunn.v1.ProxyRequest
	(*ProxyResponse)(nil),       // 4: tunn.v1.ProxyResponse
	(*HealthCheck)(nil),         // 5: tunn.v1.HealthCheck
	(*HealthCheckResponse)(nil), // 6: tunn.v1.HealthCheckResponse
	(*HttpRequest)(nil),         // 7: tunn.v1.HttpRequest
	(*HttpResponse)(nil),        // 8: tunn.v1.HttpResponse
	(*StreamClosed)(nil),        // 9: tunn.v1.StreamClosed
	(*UdpPacket)(nil),           // 10: tunn.v1.UdpPacket
	nil,                         // 11: tunn.v1.HttpRequest.HeadersEntry
	nil,                         // 12: tunn.v1.HttpResponse.HeadersEntry
}
var file_proto_tunnel_proto_depIdxs = []int32{
	1,  // 0: tunn.v1.TunnelMessage.register_client:type_name -> tunn.v1.RegisterClient
	2,  // 1: tunn.v1.TunnelMessage.register_response:type_name -> tunn.v1.RegisterResponse
	3,  // 2: tunn.v1.TunnelMessage.proxy_request:type_name -> tunn.v1.ProxyRequest
	4,  // 3: tunn.v1.TunnelMessage.proxy_response:type_name -> tunn.v1.ProxyResponse
	5,  // 4: tunn.v1.TunnelMessage.health_check:type_name -> tunn.v1.HealthCheck
	6,  // 5: tunn.v1.TunnelMessage.health_check_response:type_name -> tunn.v1.HealthCheckResponse
	7,  // 6: tunn.v1.TunnelMessage.http_request:type_name -> tunn.v1.HttpRequest
	8,  // 7: tunn.v1.TunnelMessage.http_response:type_name -> tunn.v1.HttpResponse
	9,  // 8: tunn.v1.TunnelMessage.stream_closed:type_name -> tunn.v1.StreamClosed
	10, // 9: tunn.v1.TunnelMessage.udp_packet:type_name -> tunn.v1.UdpPacket
	11, // 10: tunn.v1.HttpRequest.headers:type_name -> tunn.v1.HttpRequest.HeadersEntry
	12, // 11: tunn.v1.HttpResponse.headers:type_name -> tunn.v1.HttpResponse.HeadersEntry
	0,  // 12: tunn.v1.TunnelService.EstablishTunnel:input_type -> tunn.v1.TunnelMessage
	0,  // 13: tunn.v1.TunnelService.EstablishTunnel:output_type -> tunn.v1.TunnelMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_RegisterClient)(nil),
		(*TunnelMessage_RegisterResponse)(nil),
		(*TunnelMessage_ProxyRequest)(nil),
		(*TunnelMessage_ProxyResponse)(nil),
		(*TunnelMessage_HealthCheck)(nil),
		(*TunnelMessage_HealthCheckResponse)(nil),
		(*TunnelMessage_HttpRequest)(nil),
		(*TunnelMessage_HttpResponse)(nil),
		(*TunnelMessage_StreamClosed)(nil),
		(*TunnelMessage_UdpPacket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
