// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: proto/tunnel.proto

package tunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TunnelMessage is the envelope for all control plane messages.
// This allows multiple message types to be sent over a single bidirectional stream.
type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TunnelMessage_RegisterClient
	//	*TunnelMessage_RegisterResponse
	//	*TunnelMessage_ProxyRequest
	//	*TunnelMessage_ProxyResponse
	//	*TunnelMessage_HealthCheck
	//	*TunnelMessage_HealthCheckResponse
	Message       isTunnelMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetMessage() isTunnelMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TunnelMessage) GetRegisterClient() *RegisterClient {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_RegisterClient); ok {
			return x.RegisterClient
		}
	}
	return nil
}

func (x *TunnelMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetProxyRequest() *ProxyRequest {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_ProxyRequest); ok {
			return x.ProxyRequest
		}
	}
	return nil
}

func (x *TunnelMessage) GetProxyResponse() *ProxyResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_ProxyResponse); ok {
			return x.ProxyResponse
		}
	}
	return nil
}

func (x *TunnelMessage) GetHealthCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *TunnelMessage) GetHealthCheckResponse() *HealthCheckResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelMessage_HealthCheckResponse); ok {
			return x.HealthCheckResponse
		}
	}
	return nil
}

type isTunnelMessage_Message interface {
	isTunnelMessage_Message()
}

type TunnelMessage_RegisterClient struct {
	RegisterClient *RegisterClient `protobuf:"bytes,1,opt,name=register_client,json=registerClient,proto3,oneof"`
}

type TunnelMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,2,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type TunnelMessage_ProxyRequest struct {
	ProxyRequest *ProxyRequest `protobuf:"bytes,3,opt,name=proxy_request,json=proxyRequest,proto3,oneof"`
}

type TunnelMessage_ProxyResponse struct {
	ProxyResponse *ProxyResponse `protobuf:"bytes,4,opt,name=proxy_response,json=proxyResponse,proto3,oneof"`
}

type TunnelMessage_HealthCheck struct {
	HealthCheck *HealthCheck `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type TunnelMessage_HealthCheckResponse struct {
	HealthCheckResponse *HealthCheckResponse `protobuf:"bytes,6,opt,name=health_check_response,json=healthCheckResponse,proto3,oneof"`
}

func (*TunnelMessage_RegisterClient) isTunnelMessage_Message() {}

func (*TunnelMessage_RegisterResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_ProxyRequest) isTunnelMessage_Message() {}

func (*TunnelMessage_ProxyResponse) isTunnelMessage_Message() {}

func (*TunnelMessage_HealthCheck) isTunnelMessage_Message() {}

func (*TunnelMessage_HealthCheckResponse) isTunnelMessage_Message() {}

// RegisterClient is sent by the client (tunn serve) when it first connects
// to register a new tunnel with the proxy server.
type RegisterClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel_id is a unique identifier for this tunnel (can be generated client-side)
	TunnelId string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	// target_url is the local service to forward requests to (e.g., "http://localhost:8000")
	TargetUrl string `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	// auth_token is the shared secret for authenticating the tunnel
	AuthToken     string `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClient) Reset() {
	*x = RegisterClient{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClient) ProtoMessage() {}

func (x *RegisterClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClient.ProtoReflect.Descriptor instead.
func (*RegisterClient) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClient) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *RegisterClient) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *RegisterClient) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// RegisterResponse is sent by the server to acknowledge tunnel registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether registration succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains details if success is false
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// public_url is the publicly accessible URL for this tunnel (e.g., "https://abc123.tunn.to")
	PublicUrl     string `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

// ProxyRequest is sent by the server to instruct the client to open a new
// data connection for forwarding an incoming request.
type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id uniquely identifies this proxy connection
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// source_address is the remote client's address (for logging/debugging)
	SourceAddress string `protobuf:"bytes,2,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

// ProxyResponse is sent by the client to acknowledge a ProxyRequest.
type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_id matches the ProxyRequest
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// success indicates whether the client successfully opened the data connection
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains details if success is false
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HealthCheck is a ping message sent by either side to keep the connection alive.
type HealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the sender's current time in Unix milliseconds
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckResponse is a pong message sent in response to a HealthCheck.
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the original HealthCheck timestamp (for RTT calculation)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// response_timestamp is the responder's current time in Unix milliseconds
	ResponseTimestamp int64 `protobuf:"varint,2,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetResponseTimestamp() int64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\atunn.v1\"\xb6\x03\n" +
	"\rTunnelMessage\x12B\n" +
	"\x0fregister_client\x18\x01 \x01(\v2\x17.tunn.v1.RegisterClientH\x00R\x0eregisterClient\x12H\n" +
	"\x11register_response\x18\x02 \x01(\v2\x19.tunn.v1.RegisterResponseH\x00R\x10registerResponse\x12<\n" +
	"\rproxy_request\x18\x03 \x01(\v2\x15.tunn.v1.ProxyRequestH\x00R\fproxyRequest\x12?\n" +
	"\x0eproxy_response\x18\x04 \x01(\v2\x16.tunn.v1.ProxyResponseH\x00R\rproxyResponse\x129\n" +
	"\fhealth_check\x18\x05 \x01(\v2\x14.tunn.v1.HealthCheckH\x00R\vhealthCheck\x12R\n" +
	"\x15health_check_response\x18\x06 \x01(\v2\x1c.tunn.v1.HealthCheckResponseH\x00R\x13healthCheckResponseB\t\n" +
	"\amessage\"k\n" +
	"\x0eRegisterClient\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"p\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\"Z\n" +
	"\fProxyRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12%\n" +
	"\x0esource_address\x18\x02 \x01(\tR\rsourceAddress\"s\n" +
	"\rProxyResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"+\n" +
	"\vHealthCheck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"b\n" +
	"\x13HealthCheckResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12response_timestamp\x18\x02 \x01(\x03R\x11responseTimestamp2V\n" +
	"\rTunnelService\x12E\n" +
	"\x0fEstablishTunnel\x12\x16.tunn.v1.TunnelMessage\x1a\x16.tunn.v1.TunnelMessage(\x010\x01B-Z+github.com/behrlich/tunn/pkg/proto/tunnelv1b\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_tunnel_proto_goTypes = []any{
	(*TunnelMessage)(nil),       // 0: tunn.v1.TunnelMessage
	(*RegisterClient)(nil),      // 1: tunn.v1.RegisterClient
	(*RegisterResponse)(nil),    // 2: tunn.v1.RegisterResponse
	(*ProxyRequest)(nil),        // 3: tunn.v1.ProxyRequest
	(*ProxyResponse)(nil),       // 4: tunn.v1.ProxyResponse
	(*HealthCheck)(nil),         // 5: tunn.v1.HealthCheck
	(*HealthCheckResponse)(nil), // 6: tunn.v1.HealthCheckResponse
}
var file_proto_tunnel_proto_depIdxs = []int32{
	1, // 0: tunn.v1.TunnelMessage.register_client:type_name -> tunn.v1.RegisterClient
	2, // 1: tunn.v1.TunnelMessage.register_response:type_name -> tunn.v1.RegisterResponse
	3, // 2: tunn.v1.TunnelMessage.proxy_request:type_name -> tunn.v1.ProxyRequest
	4, // 3: tunn.v1.TunnelMessage.proxy_response:type_name -> tunn.v1.ProxyResponse
	5, // 4: tunn.v1.TunnelMessage.health_check:type_name -> tunn.v1.HealthCheck
	6, // 5: tunn.v1.TunnelMessage.health_check_response:type_name -> tunn.v1.HealthCheckResponse
	0, // 6: tunn.v1.TunnelService.EstablishTunnel:input_type -> tunn.v1.TunnelMessage
	0, // 7: tunn.v1.TunnelService.EstablishTunnel:output_type -> tunn.v1.TunnelMessage
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_RegisterClient)(nil),
		(*TunnelMessage_RegisterResponse)(nil),
		(*TunnelMessage_ProxyRequest)(nil),
		(*TunnelMessage_ProxyResponse)(nil),
		(*TunnelMessage_HealthCheck)(nil),
		(*TunnelMessage_HealthCheckResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
